# Generated by Django 5.2.11 on 2026-02-18 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('project', '0005_attachement'), ('project', '0006_rename_attachement_attachment'), ('project', '0007_alter_attachment_file'), ('project', '0008_remove_attachment_type'), ('project', '0009_alter_attachment_file')]

    dependencies = [
        ('project', '0004_merge_0002_assignment_0003_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
