# Generated by Django 5.2.12 on 2026-04-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_attachement_squashed_0009_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
