# Generated by Django 5.2.11 on 2026-02-19 00:23

import project.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_attachment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=project.storage.S3MediaStorage(), upload_to='media/'),
        ),
    ]
